"""Shared drawing style for the book's figures.

Every figure in this book is generated by a script in this directory and
written to ``figures/`` as SVG. Nothing is drawn by hand, so any figure can be
regenerated from source and audited the way a number can.

Figures are drawn on an explicit white ground rather than a transparent one:
the site renders in both light and dark themes, and a transparent figure with
dark ink disappears in the dark one.
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Ink, not colour, carries the argument. Colour is used only where a figure
# genuinely distinguishes species or phases.
INK = "#1a1a1a"
MUTED = "#6b6b6b"
FAINT = "#d4d4d4"
GROUND = "#ffffff"
AQUEOUS = "#3b6ea5"
ORGANIC = "#b8642b"
ACCENT = "#7a3b8f"
GOOD = "#2e7d4f"

RC = {
    "figure.facecolor": GROUND,
    "savefig.facecolor": GROUND,
    "axes.facecolor": GROUND,
    "font.family": "DejaVu Sans",
    "font.size": 9,
    "axes.labelsize": 9,
    "axes.titlesize": 10,
    "axes.titleweight": "normal",
    "axes.edgecolor": INK,
    "axes.labelcolor": INK,
    "axes.linewidth": 0.8,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "xtick.color": INK,
    "ytick.color": INK,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8,
    "xtick.direction": "out",
    "ytick.direction": "out",
    "legend.frameon": False,
    "legend.fontsize": 8,
    "lines.linewidth": 1.6,
    "grid.color": FAINT,
    "grid.linewidth": 0.6,
    "svg.fonttype": "path",
}


def use():
    plt.rcParams.update(RC)


def blank(ax):
    """Turn an axes into a bare drawing surface for a schematic."""
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.set_facecolor(GROUND)


def save(fig, name):
    """Write ``figures/<name>.svg`` and report the path.

    Set ``FIG_PROOF`` to a directory to get a PNG of the same figure there as
    well; that is only for looking at a draft, and is never what the book uses.
    """
    import os
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    outdir = os.path.join(root, "figures")
    if not os.path.isdir(outdir):
        outdir = os.path.join(os.getcwd(), "figures")
    out = os.path.join(outdir, name + ".svg")
    fig.savefig(out, bbox_inches="tight", pad_inches=0.05)
    proof = os.environ.get("FIG_PROOF")
    if proof:
        fig.savefig(os.path.join(proof, name + ".png"), dpi=170,
                    bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    print(out)
    return out
